config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :accounts, except: %i[new create edit update]
  resources :administrators
  resources :classrooms
  resources :contact_lists, only: %i[show] do
    resources :customers, only: %i[index]
    resources :customers, only: %i[destroy], controller: :contact_lists
  end
  resources :deposits, only: %i[new create]
  resources :investments
  resources :products
  resources :taxes
  resources :transfers, only: %i[index show new create]

  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |message| %>
    <%= render 'shared/toast', title: 'Error', message: message, primary: 'red', complement: 'white', hover: 'black' %>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="flex items-center justify-between flex-wrap bg-blue-500 px-6 py-2">
  <div class="flex items-center flex-shrink-0 text-white mr-6">
    <%= image_tag 'coin.svg', alt: 'Logo', class: 'h-10 w-10 m-2' %>
    <%= link_to root_path do %>
      <span class="font-semibold text-xl tracking-tight">RaroBank</span>
    <% end %>
  </div>
  <div class="block lg:hidden">
    <button class="nav-button flex items-center px-3 py-2 border rounded text-blue-200 border-blue-400 hover:text-white hover:border-white">
      <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="nav-content w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <% if user_signed_in? && ['Customer'].include?(current_user.userable_type) %>
        <%= link_to t('.contact_list'), contact_list_path(current_user.userable), class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.contact_lists') ? 'font-bold text-white' : 'text-blue-200'}"%>
      <% end %>
      <% if user_signed_in? && ['Root', 'Administrator'].include?(current_user.userable_type) %>
        <%= link_to t('.taxes'), taxes_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.taxes') ? 'font-bold text-white' : 'text-blue-200'}"%>
      <% end %>
      <% if user_signed_in? && ['Root', 'Administrator'].include?(current_user.userable_type) %>
        <%= link_to t('.products'), products_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.products') ? 'font-bold text-white' : 'text-blue-200'}"%>
      <% end %>
      <% if user_signed_in? && (current_user.userable_type == 'Root') %>
         <%= link_to t('.administrators'), administrators_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.administrators') ? 'font-bold text-white' : 'text-blue-200'}"%>
      <% end %>
      <% if user_signed_in? && ['Customer'].include?(current_user.userable_type) %>
        <%= link_to t('.account'), account_path(current_user.userable), class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.accounts') ? 'font-bold text-white' : 'text-blue-200'}"%>
      <% end %>
      <% if user_signed_in? && ['Root', 'Administrator'].include?(current_user.userable_type) %>
        <%= link_to t('.accounts'), accounts_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.accounts') ? 'font-bold text-white' : 'text-blue-200'}"%>
      <% end %>
      <% if user_signed_in? && ['Customer'].include?(current_user.userable_type) %>
        <%= link_to t('.product_catalog'), products_path(current_user.userable),class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.products') ? 'font-bold text-white' : 'text-blue-200'}" %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to t('.investments'), investments_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.investments') ? 'font-bold text-white' : 'text-blue-200'}"%> 
      <% end %>
      <% if user_signed_in? && ['Root', 'Administrator'].include?(current_user.userable_type) %>
        <%= link_to t('.classrooms'), classrooms_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4 #{t(".#{controller_name}") == t('.classrooms') ? 'font-bold text-white' : 'text-blue-200'}"%>
      <% end %>
      <% if user_signed_in? && ['Customer'].include?(current_user.userable_type) %>
        <%= link_to t('.transfers'), transfers_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4  #{t(".#{controller_name}") == t('.transfers') ? 'font-bold text-white' : 'text-blue-200'}"%> 
      <% end %>
      <% if user_signed_in? && ['Root', 'Administrator'].include?(current_user.userable_type) %>
        <%= link_to t('.transfers'), transfers_path, class: "block mt-4 lg:inline-block lg:mt-0 hover:text-white mr-4  #{t(".#{controller_name}") == t('.transfers') ? 'font-bold text-white' : 'text-blue-200'}"%> 
      <% end %>
    </div>
    <div>
      <% if user_signed_in? %>
        <%= link_to edit_user_registration_path, class: "block mt-4 lg:inline-block lg:mt-0 text-blue-200 hover:text-white #{controller_name == 'registrations' ? 'font-bold text-white aaa' : 'text-blue-200'}" do %> 
          <% if current_user.userable_type == 'Root' %>
            <%= Root.model_name.human %>
          <% elsif current_user.userable_type == 'Administrator' %>
            <%= Administrator.model_name.human %>
          <% else %>
            <%= current_user.userable.first_name %>
          <% end %>
        <% end %>
        

        <%= link_to t('.logout'), destroy_user_session_path, data: { turbo_method: :delete }, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 lg:mt-0"%>
      <% else %>
        <%= link_to t('.login'), new_user_session_path, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-blue-500 hover:bg-white mt-4 lg:mt-0"%>
      <% end %>
    </div>
  </div>
</nav>

<%= javascript_include_tag 'navbar' %>

app/views/shared/_notice_alert.html.erb
<div id="notice_alert" class="mx-auto" >
  <% if notice %>
    <%= render 'shared/toast', title: 'Info', message: notice, primary: 'blue', complement: 'white', hover: 'black' %>
  <% end %>
  <% if alert %>
    <%= render 'shared/toast', title: 'Error', message: alert, primary: 'red', complement: 'white', hover: 'black' %>
  <% end %>
</div>

app/views/shared/_toast.html.erb
<div class="shadow-lg rounded-lg bg-<%= primary %>-500  m-8 p-4 md:mx-32 lg:mx-32 xl:mx-64 2xl:mx-64 notification-box toast-custom">
  <div class="text-md text-<%= complement %> pb-2">
    <%= title %>
    <span class="float-right close-cross">
      <svg
        class="fill-current text-<%= complement %> hover:text-<%= hover %>"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 24 24"
        width="22"
        height="22"
        role="button"
      >
        <path
          class="heroicon-ui"
          d="M16.24 14.83a1 1 0 0 1-1.41 1.41L12 13.41l-2.83 2.83a1 1 0 0 1-1.41-1.41L10.59 12 7.76 9.17a1 1 0 0 1 1.41-1.41L12 10.59l2.83-2.83a1 1 0 0 1 1.41 1.41L13.41 12l2.83 2.83z"
        />
      </svg>
    </span>
  </div>
  <div class="text-sm   text-<%= complement %>  tracking-tight ">
    <%= message %>
  </div>
</div>

<%= javascript_include_tag 'toast' %>