config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :accounts, except: %i[new create edit update]
  resources :administrators
  resources :classrooms
  resources :contact_lists, only: %i[show] do
    resources :customers, only: %i[index]
    resources :customers, only: %i[destroy], controller: :contact_lists
  end
  resources :deposits, only: %i[new create]
  resources :investments
  resources :products
  resources :taxes
  resources :transfers, only: %i[index show new create]

  mount Sidekiq::Web => '/sidekiq'
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  has_one :user, as: :userable, dependent: :destroy
  validates :name, presence: true

  accepts_nested_attributes_for :user
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :authenticate_and_authorize!
  before_action :fetch_administrator, only: [:show, :edit, :update, :destroy]

  def index
    @administrators = Administrator.all
  end

  def show; end

  def new
    @administrator = Administrator.new
    @administrator.build_user
  end

  def edit; end

  def create
    @administrator = Administrator.new(administrator_params)

    if @administrator.save
      redirect_to administrators_path, notice: I18n.t('notices.administrator_created')
    else
      render :new
    end
  end

  def update
    if @administrator.update(administrator_params)
      return redirect_to administrators_path(@administrator), notice: t('.administrator_saved')
    end

    render :edit
  end

  def destroy
    @administrator.destroy

    redirect_to administrators_path, notice: t('.administrator_destroy')
  end

  private

  def administrator_params
    params.require(:administrator).permit(:name, user_attributes: %i[email password])
  end

  def fetch_administrator
    @administrator = Administrator.find(params[:id])
  end
end

app/views/administrators/_administrator.html.erb
<tr class="border-b dark:border-neutral-500">
  <td class="whitespace-wrap  px-0 py-2 font-medium"><%= administrator.name.truncate(20) %></td>
  <td class="whitespace-wrap  px-0 py-2 font-medium"><%= administrator.user&.email&.split('@')&.join('@ ') %></td>

  <td class="w-fit px-0 py-4 font-medium flex flex-col mx-auto">
    <% if action_name == 'index' %>
      <%= link_to administrator_path(administrator), class: 'flex justify-center w-42 my-1 bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-1 mx-1 rounded' do %>
        <div class='hidden sm:block pr-1'><%= t('show') %></div>
        <i class="fa-solid fa-circle-info"></i>
      <% end %>
    <% elsif action_name == 'show' %>

      <%= link_to edit_administrator_path(administrator), class: 'flex justify-center w-42 my-1 bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-1 mx-1 rounded' do %>
          <div class='hidden sm:block pr-1'><%= t('edit') %></div>
          <i class="fa-solid fa-pen-to-square"></i>
      <% end %>

      <%= link_to administrator_path(administrator), class: 'flex justify-center w-42 my-1 bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-1 mx-1 rounded', data: { turbo_method: :delete} do %>
          <div class='hidden sm:block pr-1'><%= t('destroy') %></div>
          <i class="fa-solid fa-trash"></i>
      <% end %>

      <%= link_to administrators_path, class: 'flex justify-center w-42 my-1 bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-1 mx-1 rounded' do %>
        <div class='hidden sm:inline-block pr-1'><%= t('back') %></div>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/administrators/_form.html.erb
<div class="flex justify-center items-center">
  <div class="bg-white p-6 rounded shadow-md mb-4">
    <%= form_with model: administrator do |form| %>
      <div><%= form.label :name, Product.human_attribute_name(:name) %></div>
      <div class="mb-4"><%= form.text_field :name %></div>

      <%= form.fields_for :user do |user_form| %>
        <div><%= user_form.label :email, User.human_attribute_name(:email) %></div>
        <div class="mb-4"><%= user_form.email_field :email %></div>

        <div><%= user_form.label :password, User.human_attribute_name(:password) %></div>
        <div class="mb-4"><%= user_form.password_field :password %></div>
      <% end %>
      

      <div class="mb-4">
        <%= form.submit t('submit'), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <%end%>
    <div>
      <% if action_name == 'new' %>
        <%= link_to t('back'), administrators_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <% elsif action_name == 'edit' %>
        <%= link_to t('back'), administrator_path(administrator), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      <%end%>
    </div>
  </div>
</div>

app/views/administrators/edit.html.erb
<%= turbo_frame_tag :container do %>
  <div class="container mx-auto text-center mb-4">
    <h2 class="text-xl font-bold mt-8"><%= t('.edit_administrator') %></h2>
  </div>

  <%= render 'shared/errors', object: @administrator %>
  <%= render 'shared/notice_alert' %>

  <%= render 'form', administrator: @administrator %>
<% end %>

app/views/administrators/index.html.erb
<%= turbo_frame_tag :container do %>
  <%= render 'shared/notice_alert' %>

  <div class="container mx-auto text-center mb-4">
    <h2 class="text-xl font-bold mt-8"><%= t('.all_administrators') %></h2>
  </div>

  <% if user_signed_in? && ['Root'].include?(current_user.userable_type) %>
    <span class="flex justify-center">
      <%= link_to t('.new_administrator'), new_administrator_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mr-2 mb-2" %>
    </span>
  <% end %>

  <div class="overflow-x-hidden w-full">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center text-sm font-light">
          <thead
            class="border-b bg-blue-500 font-medium text-white dark:border-blue-500 dark:bg-blue-500">
            <tr>
              <th scope="col" class=" px-0 py-4"><%= Administrator.human_attribute_name(:name) %></th>
              <th scope="col" class=" px-0 py-4"><%= Administrator.human_attribute_name(:email) %></th>
              <th scope="col" class=" px-0 py-4"><%= t('actions') %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @administrators %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/administrators/new.html.erb
<%= turbo_frame_tag :container do %>
  <h1 class="text-2xl font-bold mb-4"><%= t('.new_administrator') %></h1>

  <%= render 'shared/errors', object:@administrator%>
  <%= render 'shared/notice_alert' %>

  <%= render 'form', administrator: @administrator %>
<% end %>

app/views/administrators/show.html.erb
<%= turbo_frame_tag :container do %>
  <%= render 'shared/notice_alert' %>
  <div class="container mx-auto text-center mb-4">
    <h2 class="text-xl font-bold mt-8"><%= t('.administrator_details') %></h2>
  </div>

  <div class="overflow-x-hidden w-full">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full text-center text-sm font-light">
          <thead
            class="border-b bg-blue-500 font-medium text-white dark:border-blue-500 dark:bg-blue-500">
            <tr>
              <th scope="col" class=" px-0 py-4"><%= Administrator.human_attribute_name(:name) %></th>
              <th scope="col" class=" px-0 py-4"><%= Administrator.human_attribute_name(:email) %></th>
              <th scope="col" class=" px-0 py-4"><%= t('actions') %></th>
            </tr>
          </thead>
          <tbody>
            <%= render @administrator %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>